# NOTE: Generated By HttpRunner v3.1.6
# FROM: har\user\get_user_info.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseGetUserInfo(HttpRunner):

    config = Config("测试获取用户信息接口").verify(False).base_url("${get_base_url()}")

    teststeps = [
        Step(
            RunRequest("/api/get_user_info")
            .get("/api/get_user_info")
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36",
                }
            )
            .with_cookies(
                **{"session": "${get_session_id()}"}
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseGetUserInfo().test_start()
