# NOTE: Generated By HttpRunner v3.1.6
# FROM: har\login\login.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = Config("登录接口测试").verify(False).base_url("${get_base_url()}")

    teststeps = [
        Step(
            RunRequest("/api/login")
            .post("/api/login")
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36",
                }
            )
            .with_data({"user": "zhouhuajian", "pwd": "123456"})
            .validate()
            .assert_equal("status_code", 200)
            # .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal('body.message', '登录成功', '登录接口登录成功的提示消息不正确')
            .assert_equal('body.status', 1)
            .assert_length_greater_or_equals('cookies.session', 1)
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
